language: node_js

node_js:
  - node
  - 6.11.3 

services:
  - postgresql

script:
  - npm run test

env:
  - NODE_ENV=test

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info