language: node_js

services:
  - postgresql

script:
  - npm install
  - npm run test

env:
  - NODE_ENV=test

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info