
const ADD_USER = 'ADD_USER';
const LOGIN = 'LOGIN';
const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
const FETCH_USER = 'FETCH_USER';
const BORROW_BOOK = 'BORROW-BOOK';
const FETCTH_USER_BOOKS = 'FETCTH_USER_BOOKS';
const CREATE_BOOK = 'CREATE_BOOK';
const CREATE_CATEGORY = 'CREATE_CATEGORY';
const GET_CATEGORIES = 'ET_CATEGORY';
const SAVE_IMAGE = 'SAVE_IMAGE';
const SAVE_PDF = 'SAVE_PDF';
const RETURN_BOOK = 'RETURN_BOOK';
const GET_BOOK_ID = 'GET_BOOK_ID';
const EDIT_BOOK_ID = 'EDIT_BOOK_ID';
const MODIFY_BOOK = 'MODIFY_BOOK';
const DELETE_BOOK = 'DELETE_BOOK';
const GET_BORROWED_BOOKS = 'GET_BORROWED_BOOKS';
const ADMIN_GET_ALLBOOKS = 'ADMIN_GET_ALLBOOKS';
const PUBLISH_BOOK = 'PUBLISH_BOOK';
const EDIT_PROFILE = 'EDIT_PROFILE';
const EDIT_IMAGE = 'EDIT_IMAGE';
const SEND_EMAIL = 'SEND_EMAIL';
const RESET_PASS = 'RESET_PASS';
const TRENDING_BOOKS = 'TRENDING_BOOKS';
const GOOGLE_ACCESS = 'GOOGLE_ACCESS';

export {
  ADD_USER,
  LOGIN,
  GET_ALL_BOOKS,
  FETCH_USER,
  BORROW_BOOK,
  FETCTH_USER_BOOKS,
  CREATE_BOOK,
  CREATE_CATEGORY,
  GET_CATEGORIES,
  SAVE_IMAGE,
  SAVE_PDF,
  RETURN_BOOK,
  GET_BOOK_ID,
  EDIT_BOOK_ID,
  MODIFY_BOOK,
  DELETE_BOOK,
  GET_BORROWED_BOOKS,
  ADMIN_GET_ALLBOOKS,
  PUBLISH_BOOK,
  EDIT_PROFILE,
  EDIT_IMAGE,
  SEND_EMAIL,
  TRENDING_BOOKS,
  GOOGLE_ACCESS,
  RESET_PASS
};
